version: '2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    # we use image for faster developing with `npm install` already run
    image: nodexchange/marcin-js-app:dev
    command: bash -c "yarn install && npm run dev"
    environment:
      NODE_ENV: development
      HOST: 192.168.99.100
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3030:3030"
    # see: https://github.com/docker/compose/issues/2231#issuecomment-165137408
    #tty: true # problem: https://github.com/docker/compose/issues/3783
