import React, { Component } from 'react';

// eslint-disable-next-line react/prefer-stateless-function
export default class NotFound extends Component {

  render() {
    const styles = require('./Legal.scss');

    return (
      <div className={styles.containerNotFound}>
        <div id={styles.notFoundText}>
          <div className="txt">
            <h3>Verity patent marking.</h3>
            <p className="divided">The Lucie® micro drones and Kedge™ localization units are protected by one or more of the following patents:&nbsp;&nbsp;<br />• U.S. Patent Number 9885773&nbsp;<br />• U.S. Patent Number 9661472&nbsp;<br />• U.S. Patent Number 9945929&nbsp;<br /><br />OUR TRADEMARKS INCLUDE:&nbsp;<br />• Verity Studios&nbsp;<br />• The magic is real&nbsp;<br />• Lucie micro drone, charging station, guard&nbsp;<br />• Kedge localization unit&nbsp;</p>
            <h3>Introduction.</h3>
            <p className="divided">Verity Studios AG (“Verity” or "Company" or "We") respect user (“you” or “your” or “user”)  privacy and are committed to protecting it through our compliance with  this policy. We recognize that the European Union (“EU”) has an  “omnibus” data protection regime established pursuant to the General Data Protection Regulation (the “GDPR”)  and that Switzerland has a comprehensive data protection law (together,  the “Data Protection Laws”). Consistent with its pledge to protect  personal privacy, Verity Studios adheres to the applicable Data Protection Laws in Europe, Switzerland and the USA.&nbsp;<br /><br />This Privacy Policy (the “Policy”) sets forth the privacy principles that Verity follows  with respect to transfers of personal information from users to the EU  and Switzerland, including the types of information we may collect from  you or that you may provide when you visit the website veritystudios.com ("Website") and our practices for collecting, using, maintaining, protecting and disclosing that information.</p>
            <h3>Information we collect about you and how we collect it.</h3>
            <p className="">We may process data about your use of our Website (“Usage Data”). The Usage Data  may include your IP address, browser type and version, operating  system, referral source, length of visit, page views and website  navigation paths, as well as information about the timing, frequency,  and pattern of your use. This usage data may be processed for the  purposes of analyzing the use of our Website. The legal basis for this processing is our legitimate interests, namely monitoring and improving our Website.&nbsp;<br /><br />Before we collect your personal information, we will inform you about the purposes for which it is collected and used,  the types of non-agent third parties, if any, to which we disclose that  information, and the choices and means, if any, that we offer you for limiting the use and disclosure of your personal information. Notice will be provided in clear and conspicuous language when you are first asked to provide personal information to Verity, or as soon as practicable thereafter, and in any event before we use the information for a purpose other than that for which it was originally collected.</p>
            <h3>Children’s online privacy protection act compliance.</h3>
            <p className="">We are in compliance with the requirements of COPPA (Children’s Online Privacy Protection Act). Our Website is not intended for children under 13 years of age. No one under age 13 may provide any information to or on our Website. If you believe we might have any information from or about a child under 13, please <a href="contact/">contact us</a>.&nbsp;</p>
            <h3>Information you provide to us.</h3>
            <p className="divided">The  information we collect on or through our Website may include:  Information that you provide by filling in forms on our Website; Records  and copies of your correspondence (including email addresses), if you  contact us; Details of transactions you carry out through our Websites (and partner websites) and of the fulfillment of your license subscriptions. You also may provide information to be published or displayed ("Posted") on public areas of our Website or transmitted to other users of our Website or third parties (collectively, "User Contributions"). Your User Contributions are posted on and transmitted to others at your own risk.&nbsp;</p>
            <h3>Usage details, IP addresses, cookies and other technologies.</h3>
            <p className="divided">As  you navigate through and interact with our Website, we may  automatically collect certain statistical data about your equipment,  browsing actions and patterns to improve our Website and to deliver a  better and more personalized service, including:&nbsp;&nbsp;<br /><br />Details of your visits to our Website, including:&nbsp;&nbsp;<br />• traffic data&nbsp;<br />• geographical location&nbsp;<br />• logs and other communication data&nbsp;<br />• referral source&nbsp;&nbsp;<br />• the resources that you access and use on the Website&nbsp;<br /><br />Information about your computer and internet connection, including:&nbsp;<br />• your IP address&nbsp;<br />• operating system&nbsp;<br />• browser type&nbsp;<br />• browser version&nbsp;</p>
            <h3>About cookies.</h3>
            <p className="">A  cookie is a file containing an identifier (a string of letters and  numbers) that is sent by a web server to a web browser and is stored locally on your computer by your browser. The cookie identifier is then sent back to the server each time the browser requests a page from the server.<br /><br />Cookies  may be either "persistent" cookies or "session" cookies: a persistent  cookie will be stored by a web browser and will remain valid until its  set expiry date, unless deleted by the user before the expiry date; a  session cookie, on the other hand, will expire at the end of the user  session, when the web browser is closed.&nbsp;<br /><br />Cookies  do not typically contain any information that personally identifies a  user, but personal information that we store about you may be linked to  the information stored in and obtained from cookies.&nbsp;</p>
            <h3>Cookies that we use.</h3>
            <p className="divided">We use cookies for the following purposes:&nbsp;<br /><br />• Authentication - we use cookies to identify you when you visit and navigate through our Website.&nbsp;<br />• Personalization - we use cookies to store information about your preferences and to personalize our Website for you.&nbsp;<br />• Security  - we use cookies as an element of the security measures used to protect  user accounts, including preventing fraudulent use of login credentials, and to protect our Website and services generally.&nbsp;<br />• Analysis - we use cookies to help us to analyze the use and performance of our Website and services.&nbsp;</p>
            <h3>Cookies used by our service providers.</h3>
            <p className="divided">Our service providers use cookies and those cookies may be stored on your computer when you visit our Website.&nbsp;<br /><br />We use Google Analytics to anonymously analyze the use of our Website. Google Analytics gathers information about our Website’s use by means of cookies. The information gathered relating to our Website is used to create reports about the use of our Website. Google's privacy policy is available to <a target="_blank" rel="noopener" href="https://www.google.com/policies/privacy/">view here</a></p>
            <h3>Managing cookies.</h3>
            <p className="divided">Most  browsers allow you to refuse to accept cookies and to delete cookies.  The methods for doing so vary from browser to browser, and from version  to version. You can however obtain up-to-date information about blocking  and deleting cookies by contacting your browser provider.&nbsp;<br /><br />Blocking all cookies will have a negative impact upon the usability of many websites.&nbsp;<br /><br />If you block cookies, you may not be able to use all the features on our Website.&nbsp;</p>
            <h3>How we use your information.</h3>
            <p className="divided">When we collect information about you or that you provide to us, we will describe to you how we will use the information. Uses may include:&nbsp;<br /><br />• Personalization of our Website&nbsp;&nbsp;<br />• Customer support&nbsp;<br /><br />In any other way we describe when you provide the information&nbsp;In  addition, if you choose to interact with our Website by providing  additional information (e.g. contacting us) we may process your account  data (“Account Data”). The source of the Account Data is you. The account data may include:&nbsp;<br /><br />• Name&nbsp;<br />• Email address&nbsp;<br />• Contact details&nbsp;<br /><br />The Account Data  may be processed for the purposes of providing our services,  maintaining back-ups of our data bases and communicating with you. The  legal basis for this processing is consent or the performance of a  contract between you and us and/or taking steps, at your request, to  enter into such a contract.&nbsp;</p>
            <h3>Disclosure of your information.</h3>
            <p className="divided">We have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We  will use personal information only in ways that are compatible with the  purposes for which it was collected or subsequently authorized by the  individual. We will take reasonable steps to ensure that personal  information is relevant to its intended use, accurate and complete. We may disclose aggregated information about you and information that does not identify any individual without restriction. We  do not sell, trade, or otherwise transfer your personally identifiable  information to outside parties. This does not include trusted third  parties who assist us in operating our Website, conducting our business, or servicing you, as long as those parties agree to keep this information confidential.&nbsp;<br /><br />A complete list of all trusted third-parties (along with their respective privacy policies) who assist us in operating our Website, conducting our business and servicing you can be found here:&nbsp;<br /><br /><a target="_blank" rel="noopener" href="https://policies.google.com/privacy">Google</a>, <a target="_blank" rel="noopener" href="https://privacy.microsoft.com/en-us/privacystatement">Microsoft</a>, <a target="_blank" rel="noopener" href="https://mailchimp.com/legal/privacy/">MailChimp</a>, <a target="_blank" rel="noopener" href="https://www.ukfast.co.uk/">UKFAST</a></p>
            <h3>Data security.</h3>
            <p className="divided">We  have implemented measures designed to secure your personal information  from accidental loss and from unauthorized access, use, alteration and  disclosure. All information you provide to us is stored on secure and approved third-party  servers. Although we do our best to protect your personal information,  we cannot guarantee the security of your personal information  transmitted to our Website. Any transmission of personal information is  at your own risk. We are not responsible for circumvention of any  privacy settings or security measures contained on the Website.&nbsp;</p>
            <h3>Links and files.</h3>
            <p className="divided">Our Websites may contain links or information to other websites, which are provided for your convenience only. Verity  accepts no responsibility for any links, their content, or your use of  them. Access to linked websites is entirely at your own risk.&nbsp;</p>
            <h3>Notifications and correspondence data.</h3>
            <p className="divided">We may process information that you provide to us for the purpose of subscribing to our email notifications and/or newsletters ("Notification Data"). The Notification Data may be  processed for the purposes of sending you the relevant notifications  and/or newsletters. The legal basis for this processing is consent.&nbsp;&nbsp;<br /><br />We may process information contained in or relating to any communication that you send to us ("Correspondence Data"). The Correspondence Data may include the communication content and metadata associated with the communication. Our website or trusted third-party will generate the metadata associated with communications made using the website contact forms. The Correspondence Data  may be processed for the purposes of communicating with you and  record-keeping. The legal basis for this processing is our legitimate  interests, namely the proper administration of our website and business  and communications with users OR customer support and troubleshooting.&nbsp;</p>
            <h3>Data related to legal proceedings.</h3>
            <p className="divided">We  may process any of your personal data identified in this policy where  necessary for the establishment, exercise or defense of legal claims,  whether in court proceedings or in an administrative or out-of-court  procedure. The legal basis for this processing is our legitimate  interests, namely the protection and assertion of our legal rights, your  legal rights and the legal rights of others.&nbsp;<br /><br />We  may process any of your personal data identified in this policy where  necessary for the purposes of obtaining or maintaining insurance  coverage, managing risks, or obtaining professional advice. The legal  basis for this processing is our legitimate interests, namely the proper  protection of our business against risks.&nbsp;<br /><br />In  addition to the specific purposes for which we may process your  personal data, we may also process any of your personal data where such  processing is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.&nbsp;<br /><br />Please do not supply any other person's personal data to us, unless we prompt you to do so.&nbsp;</p>
            <h3>International transfers of your personal data.</h3>
            <p className="divided">In  this Section, we provide information about the circumstances in which  your personal data may be transferred to countries outside the European  Economic Area (EEA).&nbsp;<br /><br />Some of our trusted third-party suppliers are located in the United States, Switzerland and Germany. The European Commission has made an "adequacy decision" with respect to the data protection laws of each of these countries. Transfers  to each of these countries will be protected by appropriate safeguards,  namely the use of standard data protection clauses adopted or approved  by the European Commission.&nbsp;</p>
            <h3>Retaining and deleting personal data.</h3>
            <p className="divided">This section  sets out our data retention policies and procedure, which are designed  to help ensure that we comply with our legal obligations in relation to  the retention and deletion of personal data.&nbsp;<br /><br />Personal  data that we process for any purpose or purposes shall not be kept for  longer than is necessary for that purpose or those purposes.&nbsp;<br /><br />We will retain your personal data as follows:&nbsp;<br /><br />Correspondence, account, usage and Transaction Data will be retained for a maximum period of 10 years from date of submission, providing you are no longer an active customer.&nbsp;<br /><br />Notification Data will be retained for a maximum period of 2  years from date of submission. After this time, you will be notified of  the requirement to re-opt-in to continue receiving notifications. If  you choose to opt-in again, the 2-year period will start from the date  of opt-in, and you can terminate this period at any time by  unsubscribing from notifications.<br /><br />In some cases, it is not possible for us to specify in advance the periods for which your personal data will be retained. In  this case, you may contact us at any time to request this data  providing the conditions specified in the section “Your Rights” are met.&nbsp;<br /><br />Notwithstanding  the other provisions of this Section 6, we may retain your personal  data where such retention is necessary for compliance with a legal  obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.&nbsp;<br /><br />You can review and change your personal information by contacting us to  access, correct or delete any personal information that you have  provided to us so long as making such change does not violate any law or  legal requirement or cause the information to be incorrect.&nbsp;</p>
            <h3>Your rights.</h3>
            <p className="divided">Your principal rights under data protection law are:&nbsp;<br /><br />• the right to access&nbsp;<br />• the right to rectification&nbsp;<br />• the right to erasure&nbsp;<br />• the right to restrict processing&nbsp;<br />• the right to object to processing&nbsp;<br />• the right to data portability&nbsp;<br />• the right to complain to a supervisory authority&nbsp;<br />• the right to withdraw consent&nbsp;<br /><br />You may instruct us by writing to provide you with any personal information we hold about you; provision of such information will be subject to:&nbsp;&nbsp;<br /><br />• the payment of a fee (currently fixed at CHF 50); and&nbsp;<br />• the supply of appropriate evidence of your identity (for this purpose, we  will usually accept a photocopy of your passport certified by a  solicitor or bank plus an original copy of a utility bill showing your  current address).&nbsp;<br />• We may withhold personal information that you request to the extent permitted by law.&nbsp;<br />• You may instruct us at any time not to process your personal information for marketing purposes.&nbsp;</p>
            <h3>Liability.</h3>
            <p className="divided">VERITY STUDIOS  AND ITS AFFILIATES WILL NOT BE LIABLE (WHETHER IN AN ACTION IN  NEGLIGENCE, CONTRACT OR TORT OR BASED ON A WARRANTY OR OTHERWISE), IN  ANY EVENT, FOR ANY LOSS, DAMAGE, EXPENSE, LOSS OF PROFITS, REVENUE, OR  LOSS OR INACCURACY OF DATA, OR ANY DIRECT, INDIRECT, INCIDENTAL,  PUNITIVE, SPECIAL OR CONSEQUENTIAL DAMAGES, EVEN IF VERITY  OR ITS REPRESENTATIVES ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES,  IN CONNECTION WITH (I) YOUR RELIANCE ON OR USE OR INABILITY TO USE THE  CONTENT AND INFORMATION OF THIS WEBSITE OR ANY LINKED WEBSITE, (II) ANY  FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN  OPERATION OR TRANSMISSION, COMPUTER VIRUS OR LINE OR SYSTEM FAILURE OF  THIS WEBSITE OR ANY LINKED WEBSITE, (III) THE COST OF PROCUREMENT OF  SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA,  INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR  TRANSACTIONS ENTERED INTO THROUGH OR FROM THIS WEBSITE; (IV)  UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (V)  STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON OUR WEBSITE; OR (VI) ANY  OTHER MATTER RELATING TO OUR WEBSITE. IN NO EVENT SHALL OUR TOTAL  LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION (WHETHER  IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE), OR  OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING OUR  WEBSITE. IF YOU ARE DISSATISFIED WITH ANY PORTION OF OUR WEBSITE, OR  WITH ANY OF THESE TERMS AND CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY  IS THE DISCONTINUATION OF YOUR USE OF THIS WEBSITE. IF ANY PORTION OF  THIS LIMITATION OF LIABILITY IS FOUND TO BE INVALID, LIABILITY IS  LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.&nbsp;VERITY  IS NOT LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY ANY HARMFUL MATERIAL  COLLECTED THROUGH YOUR USE OF THE WEBSITE, LINKS, OR DOWNLOADS. USE OF  THE WEBSITE IS AT YOUR OWN RISK. CONTENT AND SERVICES OR ITEMS OBTAINED  THROUGH THE WEBSITE ARE PROVIDED ‘AS IS’, WITHOUT ANY WARRANTIES, EITHER  EXPRESS OR IMPLIED.&nbsp;</p>
            <h3>Dispute Resolution.</h3>
            <p className="divided">Any questions or concerns regarding the use or disclosure of personal information should be directed to Verity via our contact page. We  will investigate and attempt to resolve complaints and disputes  regarding use and disclosure of personal information in accordance with  the principles contained in this Policy.&nbsp;&nbsp;</p>
            <h3>Compliance with court orders &amp; law enforcement agencies.</h3>
            <p className="divided">We may disclose personal information without notification in order to comply with a legal requirement, court order, or subpoena, or to cooperate with law enforcement or government agencies.&nbsp;</p>
            <h3>Merger, sale, transfer of corporate assets or reorganization.</h3>
            <p className="divided">We  may transfer information as part of any corporate merger, sale,  acquisition, transfer of assets, or reorganization without notice. Such  transfer will be on the basis of the continuation of all privacy rights set out in this document.&nbsp;</p>
            <h3>Your consent.</h3>
            <p className="divided">By using our Website, you consent to our privacy policy.&nbsp;</p>
            <h3>Changes to our privacy policy.</h3>
            <p className="divided">This Policy may be amended from time to time, consistent with the requirements of the E.U. and Swiss Data Protection Laws. It is our policy to post any changes we make to our privacy policy on this page.&nbsp;</p>
            <h3>Contact information.</h3>
            <p className="divided">Verity Studios AG<br />Binzmühlestrasse 81&nbsp;<br />8050 Zurich&nbsp;<br />Switzerland&nbsp;&nbsp;+41 44 533 83 60<br /><a href="mailto:info@veritystudios.com">info@veritystudios.com&nbsp;</a></p>
          </div>
        </div>
        <div id={styles.upset}>{''}</div>
      </div>
    );
  }
}
